ucsb-cs156-s24/team03-s24-5pm-7

src/main/java/edu/ucsb/cs156/example/controllers/ArticlesController.java
src/main/java/edu/ucsb/cs156/example/entities/Articles.java
src/main/java/edu/ucsb/cs156/example/repositories/ArticlesRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/ArticlesControllerTests.java

Close #53 
-copied from team02
-with all backend files for articles

 Copy files for Backend CRUD API Articles from team02

---

src/main/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemController.java
src/main/java/edu/ucsb/cs156/example/entities/UCSBDiningCommonsMenuItem.java
src/main/java/edu/ucsb/cs156/example/repositories/UCSBDiningCommonsMenuItemRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemControllerTests.java

Copied over backend files from team02
Closes #8

kl - copied backend files from team02

---

pom.xml
src/main/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationController.java
src/main/java/edu/ucsb/cs156/example/entities/UCSBOrganization.java
src/main/java/edu/ucsb/cs156/example/repositories/UCSBOrganizationRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationControllerTests.java

added backend files for organization

---

frontend/src/fixtures/ucsbOrganizationFixtures.js
pom.xml
src/main/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationController.java
src/main/java/edu/ucsb/cs156/example/entities/UCSBOrganization.java
src/main/java/edu/ucsb/cs156/example/repositories/UCSBOrganizationRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationControllerTests.java

Aneesh organization fixture

---

frontend/src/fixtures/ucsbDiningCommonsMenuItemFixtures.js
src/main/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemController.java
src/main/java/edu/ucsb/cs156/example/entities/UCSBDiningCommonsMenuItem.java
src/main/java/edu/ucsb/cs156/example/repositories/UCSBDiningCommonsMenuItemRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemControllerTests.java

Added fixtures for DiningCommonsMenuItem
Closes #9

Kate menu item fixtures

---

src/main/java/edu/ucsb/cs156/example/controllers/UCSBRecommendationRequestController.java
src/main/java/edu/ucsb/cs156/example/entities/UCSBRecommendationRequest.java
src/main/java/edu/ucsb/cs156/example/repositories/UCSBRecommendationRequestRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/UCSBRecommendationRequestControllerTests.java

Added all the backend files for RecommendationRequest
Closes #26

added backend for RecommendationRequest

---

frontend/src/fixtures/recommendationRequestFixtures.js
src/main/java/edu/ucsb/cs156/example/controllers/UCSBRecommendationRequestController.java
src/main/java/edu/ucsb/cs156/example/entities/UCSBRecommendationRequest.java
src/main/java/edu/ucsb/cs156/example/repositories/UCSBRecommendationRequestRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/UCSBRecommendationRequestControllerTests.java

Adil recommendation request fixtures

---

frontend/src/main/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemForm.js
frontend/src/stories/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemForm.stories.js
frontend/src/tests/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemForm.test.js

Added form + tests and stories
Closes #10

Kate menu item form

---

frontend/src/main/components/UCSBOrganization/UCSBOrganizationForm.js
frontend/src/stories/components/UCSBOrganization/UCSBOrganizationForm.stories.js
frontend/src/tests/components/UCSBOrganization/UCSBOrganizationForm.test.js

form components

---

frontend/src/main/components/UCSBOrganization/UCSBOrganizationTable.js
frontend/src/main/utils/UCSBOrganizationUtils.js
frontend/src/stories/components/UCSBOrganization/UCSBOrganizationTable.stories.js
frontend/src/tests/components/UCSBOrganization/UCSBOrganizationTable.test.js
frontend/src/tests/utils/UCSBOrganizationUtils.test.js

Tables component + tests

---

frontend/src/main/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemTable.js
frontend/src/stories/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemForm.stories.js
frontend/src/stories/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemTable.stories.js
frontend/src/tests/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemForm.test.js
frontend/src/tests/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemTable.test.js

Added table + tests + stories
Closes #11

Kate menu item table

---

frontend/src/fixtures/articlesFixtures.js

- added fixture.js for article
- here is oneArticle and threeArticles inside
- Close #54

Create fixtures for Articles

---

src/main/java/edu/ucsb/cs156/example/controllers/MenuItemReviewController.java
src/main/java/edu/ucsb/cs156/example/entities/MenuItemReview.java
src/main/java/edu/ucsb/cs156/example/repositories/MenuItemReviewRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/MenuItemReviewControllerTests.java

kk - copy backend files from team02

---

frontend/src/App.js
frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.js
frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.js
frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.js
frontend/src/tests/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemTable.test.js
frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.test.js
frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.test.js
frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.test.js

Added placeholders for menu item
Closes #12

Kate menu item placeholders

---

frontend/src/fixtures/ucsbDiningCommonsMenuItemFixtures.js
frontend/src/main/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemTable.js
frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.js
frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.js
frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.js
frontend/src/main/utils/ucsbDiningCommonsMenuItemUtils.js
frontend/src/stories/pages/Restaurants/RestaurantCreatePage.stories.js
frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.stories.js
frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.stories.js
frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.stories.js
frontend/src/tests/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemTable.test.js
frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.test.js
frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.test.js
frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.test.js

kl - added index page for menu item
Closes #14

Kate menu item index

---

frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.js
frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.js
frontend/src/stories/pages/Restaurants/RestaurantCreatePage.stories.js
frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.stories.js
frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.stories.js
frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.test.js
frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.test.js

kl - filled out menu item edit page + tests + stories
Closes #15

Kate menu item edit page

---

frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.js
frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.test.js
frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.test.js

Reverts ucsb-cs156-s24/team03-s24-5pm-7#81

Revert "Kate menu item create page"

---

frontend/src/fixtures/menuItemReviewFixtures.js

kk - menu item review fixtures

---

frontend/src/fixtures/recommendationRequestFixtures.js
frontend/src/main/components/RecommendationRequest/RecommendationRequestForm.js
frontend/src/tests/components/RecommendationRequest/RecommendationRequestForm.test.js
frontend/src/tests/components/UCSBDates/UCSBDateForm.test.js

bug fix + form + test

---

src/main/java/edu/ucsb/cs156/example/controllers/UCSBHelpRequestController.java
src/main/java/edu/ucsb/cs156/example/entities/UCSBHelpRequest.java
src/main/java/edu/ucsb/cs156/example/repositories/UCSBHelpRequestRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/UCSBHelpRequestControllerTests.java

Copy files for Backend CRUD API HelpRequest from team02
Closes #44

Add Help Request Backend

---

frontend/src/App.js
frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/pages/UCSBOrganization/UCSBOrganizationCreatePage.js
frontend/src/main/pages/UCSBOrganization/UCSBOrganizationEditPage.js
frontend/src/main/pages/UCSBOrganization/UCSBOrganizationIndexPage.js
frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationCreatePage.test.js
frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationEditPage.test.js
frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationIndexPage.test.js

Aneesh organization new placeholders

---

frontend/src/fixtures/helpRequestFixtures.js
src/main/java/edu/ucsb/cs156/example/controllers/UCSBHelpRequestController.java
src/main/java/edu/ucsb/cs156/example/entities/UCSBHelpRequest.java
src/main/java/edu/ucsb/cs156/example/repositories/UCSBHelpRequestRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/UCSBHelpRequestControllerTests.java

Create fixtures for HelpRequest
Closes #45

Help Request fixtures

---

frontend/src/fixtures/menuItemReviewFixtures.js
frontend/src/main/components/MenuItemReview/MenuItemReviewForm.js
frontend/src/stories/components/MenuItemReview/MenuItemReviewForm.stories.js
frontend/src/tests/components/MenuItemReview/MenuItemReviewForm.test.js

Implemented menu item review form component and tests.
Storybook link: https://ucsb-cs156-s24.github.io/team03-s24-5pm-7/prs/97/storybook/?path=/story/components-menuitemreview-menuitemreviewform--create
Closes #37

Kk menu item review form component

---

frontend/src/fixtures/menuItemReviewFixtures.js
frontend/src/main/components/MenuItemReview/MenuItemReviewForm.js
frontend/src/main/components/MenuItemReview/MenuItemReviewTable.js
frontend/src/main/utils/MenuItemReviewUtils.js
frontend/src/stories/components/MenuItemReview/MenuItemReviewForm.stories.js
frontend/src/stories/components/MenuItemReview/MenuItemReviewTable.stories.js
frontend/src/tests/components/MenuItemReview/MenuItemReviewForm.test.js
frontend/src/tests/components/MenuItemReview/MenuItemReviewTable.test.js
frontend/src/tests/utils/MenuItemReviewUtils.test.js

Implemented menu item review table component and tests.
Storybook link: https://ucsb-cs156-s24.github.io/team03-s24-5pm-7/prs/99/storybook/?path=/story/components-menuitemreview-menuitemreviewtable--three-items-admin-user
Closes #38

Kk menu item review table component

---

frontend/src/App.js
frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/pages/HelpRequest/HelpRequestCreatePage.js
frontend/src/main/pages/HelpRequest/HelpRequestEditPage.js
frontend/src/main/pages/HelpRequest/HelpRequestIndexPage.js
frontend/src/tests/pages/HelpRequest/HelpRequestCreatePage.test.js
frontend/src/tests/pages/HelpRequest/HelpRequestEditPage.test.js
frontend/src/tests/pages/HelpRequest/HelpRequestIndexPage.test.js

Copy Placeholders for HelpRequest pages; add to App.js/AppNavbar.js
Closes #48

Help Request Placeholders

---

frontend/src/main/components/RecommendationRequest/RecommendationRequestTable.js
frontend/src/main/utils/recommendationRequestUtils.js
frontend/src/tests/components/RecommendationRequest/RecommendationRequestTable.test.js
frontend/src/tests/utils/recommendationRequestUtils.test.js

Adil recommendation request table

---

frontend/src/App.js
frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/pages/MenuItemReview/MenuItemReviewCreatePage.js
frontend/src/main/pages/MenuItemReview/MenuItemReviewEditPage.js
frontend/src/main/pages/MenuItemReview/MenuItemReviewIndexPage.js
frontend/src/tests/pages/MenuItemReview/MenuItemReviewCreatePage.test.js
frontend/src/tests/pages/MenuItemReview/MenuItemReviewEditPage.test.js
frontend/src/tests/pages/MenuItemReview/MenuItemReviewIndexPage.test.js

Copied placeholders for Menu Item Review pages
Closes #39

kk - copy placeholders for menu item review

---

frontend/src/main/components/UCSBOrganization/UCSBOrganizationTable.js
frontend/src/main/pages/UCSBOrganization/UCSBOrganizationEditPage.js
frontend/src/stories/pages/UCSBOrganization/UCSBOrganizationEditPage.stories.js
frontend/src/stories/pages/UCSBOrganization/UCSBOrganizationIndexPage.stories.js
frontend/src/tests/components/UCSBOrganization/UCSBOrganizationTable.test.js
frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationEditPage.test.js

Aneesh organization edit

---

frontend/src/main/pages/HelpRequest/HelpRequestCreatePage.js
frontend/src/stories/pages/HelpRequest/HelpRequestCreatePage.stories.js
frontend/src/tests/pages/HelpRequest/HelpRequestCreatePage.test.js

Create Page for HelpRequest plus tests and stories
Closes #49

Help Request Create Page

---

frontend/src/main/pages/HelpRequest/HelpRequestCreatePage.js
frontend/src/main/pages/HelpRequest/HelpRequestIndexPage.js
frontend/src/stories/pages/HelpRequest/HelpRequestCreatePage.stories.js
frontend/src/stories/pages/HelpRequest/HelpRequestIndexPage.stories.js
frontend/src/tests/pages/HelpRequest/HelpRequestCreatePage.test.js
frontend/src/tests/pages/HelpRequest/HelpRequestIndexPage.test.js

Index Page for HelpRequest plus tests and stories
Closes #50

Help Request Index Page

---

frontend/src/main/pages/MenuItemReview/MenuItemReviewCreatePage.js
frontend/src/stories/pages/MenuItemReview/MenuItemReviewCreatePage.stories.js
frontend/src/tests/pages/MenuItemReview/MenuItemReviewCreatePage.test.js

Added create page for menu item review plus tests and stories.
Storybook link: https://ucsb-cs156-s24.github.io/team03-s24-5pm-7/prs/120/storybook/?path=/story/components-menuitemreview-menuitemreviewform--create
To test create page, enter the item ID, reviewer email, stars, date reviewed, and comments.
When you submit an entry with a missing parameter, appropriate error message is displayed.
Closes #40

kk - create page for menu item review

---

frontend/src/main/pages/HelpRequest/HelpRequestCreatePage.js
frontend/src/main/pages/HelpRequest/HelpRequestEditPage.js
frontend/src/main/pages/HelpRequest/HelpRequestIndexPage.js
frontend/src/stories/pages/HelpRequest/HelpRequestCreatePage.stories.js
frontend/src/stories/pages/HelpRequest/HelpRequestEditPage.stories.js
frontend/src/stories/pages/HelpRequest/HelpRequestIndexPage.stories.js
frontend/src/tests/pages/HelpRequest/HelpRequestCreatePage.test.js
frontend/src/tests/pages/HelpRequest/HelpRequestEditPage.test.js
frontend/src/tests/pages/HelpRequest/HelpRequestIndexPage.test.js

Edit Page for HelpRequest plus tests and stories
Closes #51

Help Request Edit Page

---

frontend/src/fixtures/menuItemReviewFixtures.js
frontend/src/main/pages/MenuItemReview/MenuItemReviewEditPage.js
frontend/src/main/pages/MenuItemReview/MenuItemReviewIndexPage.js
frontend/src/stories/pages/MenuItemReview/MenuItemReviewEditPage.stories.js
frontend/src/stories/pages/MenuItemReview/MenuItemReviewIndexPage.stories.js
frontend/src/tests/pages/MenuItemReview/MenuItemReviewEditPage.test.js
frontend/src/tests/pages/MenuItemReview/MenuItemReviewIndexPage.test.js

Added edit page for menu item review plus tests and stories.
Storybook link: https://ucsb-cs156-s24.github.io/team03-s24-5pm-7/prs/125/storybook/?path=/story/pages-menuitemreview-menuitemrevieweditpage--default
Closes #42

Kk menu item review edit page

---

frontend/src/fixtures/menuItemReviewFixtures.js
frontend/src/main/pages/MenuItemReview/MenuItemReviewIndexPage.js
frontend/src/stories/pages/MenuItemReview/MenuItemReviewIndexPage.stories.js
frontend/src/tests/pages/MenuItemReview/MenuItemReviewIndexPage.test.js

Added index page for menu item review plus tests and stories.
Storybook link: https://ucsb-cs156-s24.github.io/team03-s24-5pm-7/prs/123/storybook/?path=/story/pages-menuitemreview-menuitemreviewindexpage--empty
Closes #41

kk - index page for menu item review

---

frontend/src/App.js
frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/pages/RecommendationRequest/RecommendationRequestCreatePage.js
frontend/src/main/pages/RecommendationRequest/RecommendationRequestEditPage.js
frontend/src/main/pages/RecommendationRequest/RecommendationRequestIndexPage.js
frontend/src/stories/pages/RecommendationRequest/RecommendationRequestCreatePage.stories.js
frontend/src/tests/pages/RecommendationRequest/RecommendationRequestCreatePage.test.js
frontend/src/tests/pages/RecommendationRequest/RecommendationRequestEditPage.test.js
frontend/src/tests/pages/RecommendationRequest/RecommendationRequestIndexPage.test.js

Adil recommendation request create page

---

.env.SAMPLE
.gitignore
frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/components/RecommendationRequest/RecommendationRequestTable.js
frontend/src/main/pages/RecommendationRequest/RecommendationRequestCreatePage.js
frontend/src/main/pages/RecommendationRequest/RecommendationRequestEditPage.js
frontend/src/main/pages/RecommendationRequest/RecommendationRequestIndexPage.js
frontend/src/stories/pages/RecommendationRequest/RecommendationRequestEditPage.stories.js
frontend/src/stories/pages/RecommendationRequest/RecommendationRequestIndexPage.stories.js
frontend/src/tests/components/RecommendationRequest/RecommendationRequestTable.test.js
frontend/src/tests/pages/RecommendationRequest/RecommendationRequestCreatePage.test.js
frontend/src/tests/pages/RecommendationRequest/RecommendationRequestEditPage.test.js
frontend/src/tests/pages/RecommendationRequest/RecommendationRequestIndexPage.test.js

Closes #30
Closes #31 
Closes #32 
Closes #33

Adil recommendation request index page

---

frontend/src/main/components/Articles/ArticlesTable.js
frontend/src/main/pages/Articles/ArticlesCreatePage.js
frontend/src/main/pages/Articles/ArticlesEditPage.js
frontend/src/main/pages/Articles/ArticlesIndexPage.js
frontend/src/main/utils/ArticleUtlis.js
frontend/src/stories/components/Articles/ArticlesTable.stories.js
frontend/src/stories/pages/Articles/ArticlesCreatePage.stories.js
frontend/src/stories/pages/Articles/ArticlesEditPage.stories.js
frontend/src/stories/pages/Articles/ArticlesIndexPage.stories.js
frontend/src/tests/pages/Articles/ArticlesCreatePage.test.js
frontend/src/tests/pages/Articles/ArticlesEditPage.test.js
frontend/src/tests/pages/Articles/ArticlesIndexPage.test.js
frontend/src/tests/utils/articlesUtils.test.js

- Close #58 
- implemented create page
- added create.stories
- added create test
- Close #59 
- implemented index page
- added index.stories
- added index test
- Close #60 
- implemented edit page
- added edit.stories
- added edit test

Create Page for Articles plus tests and stories

---

src/main/java/edu/ucsb/cs156/example/controllers/HelpRequestController.java
src/main/java/edu/ucsb/cs156/example/entities/HelpRequest.java
src/main/java/edu/ucsb/cs156/example/repositories/HelpRequestRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/RequestControllerTests.java

Should display index page, now.

Fix Help Request Backend

---

frontend/src/main/components/Articles/ArticlesTable.js
frontend/src/tests/components/Articles/ArticlesTable.test.js

It cannot delete item before,
which caused by resolving merge conflicts
right it works.

After merge, this is a mistake

---

frontend/src/main/components/MenuItemReview/MenuItemReviewTable.js
frontend/src/main/pages/MenuItemReview/MenuItemReviewCreatePage.js
frontend/src/main/pages/MenuItemReview/MenuItemReviewEditPage.js
frontend/src/main/pages/MenuItemReview/MenuItemReviewIndexPage.js
frontend/src/main/utils/MenuItemReviewUtils.js
frontend/src/stories/components/MenuItemReview/MenuItemReviewTable.stories.js
frontend/src/stories/pages/MenuItemReview/MenuItemReviewCreatePage.stories.js
frontend/src/stories/pages/MenuItemReview/MenuItemReviewEditPage.stories.js
frontend/src/stories/pages/MenuItemReview/MenuItemReviewIndexPage.stories.js
frontend/src/tests/pages/MenuItemReview/MenuItemReviewCreatePage.test.js
frontend/src/tests/pages/MenuItemReview/MenuItemReviewEditPage.test.js
frontend/src/tests/pages/MenuItemReview/MenuItemReviewIndexPage.test.js
frontend/src/tests/utils/MenuItemReviewUtils.test.js

Fixed api issue. Should display index page now.

fixed api mismatch
